services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      additional_contexts:
        backend: ./backend
    container_name: boerbert-frontend
    ports:
      - "4323:80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: boerbert-backend
    volumes:
      # Keep source code in sync (optional)
      - ./src:/app/src
      # IMPORTANT: mount the static folder
      - ./public:/app/public
    environment:
      NODE_ENV: development
    ports:
      - "7656:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped