services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      additional_contexts:
        backend: ./backend
    container_name: boerbert-frontend
    ports:
      - "4323:80"
    environment:
      NODE_ENV: production
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: boerbert-backend
    volumes:
      # HIER STAAN DE PLAAAATJES LOLOL
      - ./.boerbert-assets:/app/public
    ports:
      - "7656:3000"
    environment:
      NODE_ENV: production
    env_file:
      - ./backend/.env
    restart: unless-stopped